version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:18.12.1
      - image: circleci/node:18.12.1
    steps:
      - checkout
      - run:
          name: install-dependent
          command: npm install
      - run:
          name: build
          command: npm run build